# Generated by Django 4.2 on 2024-06-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_tags_tag_tags_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.FloatField(verbose_name='Цена со скидкой')),
                ('dateFrom', models.DateField(verbose_name='Начало акции')),
                ('dateTo', models.DateField(verbose_name='Конец акции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['pk'],
            },
        ),
    ]
