# Generated by Django 4.2 on 2024-06-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_salesproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleProduct',
        ),
    ]
